language: cpp

os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      env:
        - SETUP="./setup-linux.sh"
  include:
    - os: osx
      env:
        - SETUP="./setup-osx.sh"

before_install:
    - eval "${SETUP}"
