#ifndef DOCUMENTDATABASE_GLOBAL_H
#define DOCUMENTDATABASE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DOCUMENTDATABASE_LIBRARY)
#  define DOCUMENTDATABASESHARED_EXPORT Q_DECL_EXPORT
#else
#  define DOCUMENTDATABASESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DOCUMENTDATABASE_GLOBAL_H
